AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sagemaker-housekeeping

  Sample SAM Template for sagemaker-housekeeping

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HouseKeeperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: housekeeper/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
#      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HouseKeeperApi:
    Description: "API Gateway endpoint URL for Prod stage for HouseKeeper function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HouseKeeperFunction:
    Description: "HouseKeeper Lambda Function ARN"
    Value: !GetAtt HouseKeeperFunction.Arn
  HouseKeeperFunctionIamRole:
    Description: "Implicit IAM Role created for HouseKeeper function"
    Value: !GetAtt HouseKeeperFunctionRole.Arn
